version: '3.8'

services:
  app:
    build: .
    container_name: fileextension-app-prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: always
